### ISSUE TITLE
Single click bug  and PR

### ISSUE THREAD

**Issue by alexiscott** [sandropibia/Leaflet.SelectAreaFeature#9] opened 2018-05-16 15:53 UTC
Hi @sandropibia 

I came across what I think is a bug and have added a PR here to fix it: https://github.com/sandropibia/Leaflet.SelectAreaFeature/pull/8
# Steps to reproduce the bug
- Visit https://sandropibia.github.io/Leaflet.SelectAreaFeature/examples/index.html
- Open dev tools console
- Click on "Enable"
- Single click somewhere on the map without moving the mouse afterwards
- Click the get polygon features button
- you will see an error in the console typeError: this._southWest is undefined

**Comment by sandropibia** [comment] 2021-01-30 15:39
Hello Alex, I can't reproduce it and why should you after enabled it, not to draw anything?

**Comment by sandropibia** [comment] 2021-01-30 17:12
I'll close this one, for me it is not a issue

**Comment by Wurzelkoch** [comment] 2023-07-10 17:00
I see the same error even after drawing something, so the button 'get polygon features' in the demo does not work at all.

**Comment by sandropibia** [comment] 2023-07-10 19:08
you must select some polygons to work and disable it first

**Closed as completed** 2023-07-10 19:09 UTC
